runtime: go
api_version: go1
vm: true

manual_scaling:
  instances: 1

handlers:
- url: /favicon.ico
  static_files: web/favicon.ico
  upload: web/favicon.ico
- url: /style
  static_dir: web/style
- url: /script
  static_dir: web/script
- url: /.*
  script: _go_app